services:
  - type: web
    name: ffmpeg-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
    autoDeploy: true
